# Generated by Django 4.2 on 2023-05-12 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cproyeccion',
            name='asignaturas',
            field=models.ManyToManyField(related_name='cproyecciones', to='Cronorgama.asignaturas'),
        ),
        migrations.AlterField(
            model_name='proyeccion',
            name='Cproyeccion',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='Cronorgama.cproyeccion'),
        ),
    ]
