# Generated by Django 4.2 on 2023-05-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0002_alter_cproyeccion_asignaturas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyeccion',
            old_name='Cproyeccion',
            new_name='cproyeccion',
        ),
    ]
