# Generated by Django 4.2 on 2023-05-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0003_rename_cproyeccion_proyeccion_cproyeccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='id_asignaturas',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='id_authuser',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='id_programas',
        ),
        migrations.RemoveField(
            model_name='cproyeccion',
            name='asignaturas',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='id_authuser',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='proyeccion',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='usuario_emisor',
        ),
        migrations.RemoveField(
            model_name='mensajes',
            name='usuarios_destinatarios',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='id_asignaturas',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='id_authuser',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='id_programas',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='id_salon',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='jornada',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='username',
        ),
        migrations.RemoveField(
            model_name='proyeccion',
            name='cproyeccion',
        ),
        migrations.RemoveField(
            model_name='proyeccion',
            name='programas',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='id_bitacora',
        ),
        migrations.DeleteModel(
            name='Asignaturas',
        ),
        migrations.DeleteModel(
            name='Bitacora',
        ),
        migrations.DeleteModel(
            name='Cproyeccion',
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
        migrations.DeleteModel(
            name='Mensajes',
        ),
        migrations.DeleteModel(
            name='Programacion',
        ),
        migrations.DeleteModel(
            name='Programas',
        ),
        migrations.DeleteModel(
            name='Proyeccion',
        ),
        migrations.DeleteModel(
            name='RegistroAsistencia',
        ),
        migrations.DeleteModel(
            name='Salon',
        ),
        migrations.DeleteModel(
            name='TipoJornada',
        ),
    ]
