# Generated by Django 4.2 on 2023-05-12 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0004_remove_bitacora_id_asignaturas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('creditos', models.IntegerField()),
                ('intensidad', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('semana', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
                ('Tema', models.CharField(max_length=200)),
                ('id_asignaturas', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.asignaturas')),
                ('id_authuser', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cproyeccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_semanas', models.IntegerField(blank=True, null=True)),
                ('num_docentes', models.IntegerField(blank=True, default=0, null=True)),
                ('asignaturas', models.ManyToManyField(related_name='cproyecciones', to='Cronorgama.asignaturas')),
            ],
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoJornada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=200)),
                ('semana', models.CharField(max_length=200)),
                ('fecha_recuperar', models.CharField(max_length=200)),
                ('tema_recuperar', models.CharField(max_length=200)),
                ('total_hora', models.CharField(max_length=200)),
                ('hora_entrada', models.CharField(max_length=200)),
                ('hora_salida', models.CharField(max_length=200)),
                ('id_bitacora', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.bitacora')),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('semestre', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('cproyeccion', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proyecciones', to='Cronorgama.cproyeccion')),
                ('programas', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.programas')),
            ],
        ),
        migrations.AddField(
            model_name='programas',
            name='jornada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.tipojornada'),
        ),
        migrations.AddField(
            model_name='programas',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=200)),
                ('dia', models.CharField(max_length=200)),
                ('id_asignaturas', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.asignaturas')),
                ('id_authuser', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_programas', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.programas')),
                ('id_salon', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.salon')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('mensaje', models.CharField(max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('confirmar', models.BooleanField(default=True)),
                ('proyeccion', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.proyeccion')),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('usuarios_destinatarios', models.ManyToManyField(related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=200)),
                ('hora_inicio', models.CharField(max_length=200)),
                ('hora_fin', models.CharField(max_length=200)),
                ('id_authuser', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bitacora',
            name='id_programas',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.programas'),
        ),
        migrations.AddField(
            model_name='asignaturas',
            name='programa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.programas'),
        ),
    ]
