# Generated by Django 4.2 on 2023-05-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0005_asignaturas_bitacora_cproyeccion_programas_salon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cproyeccion',
            name='asignaturas',
        ),
        migrations.RemoveField(
            model_name='cproyeccion',
            name='num_docentes',
        ),
        migrations.RemoveField(
            model_name='cproyeccion',
            name='total_semanas',
        ),
        migrations.CreateModel(
            name='Casignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_semanas', models.IntegerField(blank=True, null=True)),
                ('num_docentes', models.IntegerField(blank=True, default=0, null=True)),
                ('asignaturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cproyecciones', to='Cronorgama.asignaturas')),
            ],
        ),
        migrations.AddField(
            model_name='cproyeccion',
            name='Casignatura',
            field=models.ManyToManyField(related_name='cproyecciones', to='Cronorgama.casignatura'),
        ),
    ]
