# Generated by Django 4.2 on 2023-05-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0006_remove_cproyeccion_asignaturas_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
