# Generated by Django 4.2 on 2023-05-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0008_cdisponibilidad_dia_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidad',
            name='Profesor',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='cdisponibilidad',
        ),
        migrations.DeleteModel(
            name='Cdisponibilidad',
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
