# Generated by Django 4.2 on 2023-05-13 20:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0011_remove_cdisponibilidad_cdia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(default=0)),
                ('b', models.BooleanField(default=0)),
                ('c', models.BooleanField(default=0)),
                ('d', models.BooleanField(default=0)),
                ('e', models.BooleanField(default=0)),
                ('dia', models.ForeignKey(blank=True, default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.dia')),
            ],
        ),
        migrations.CreateModel(
            name='Cdisponibilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cdia', models.ManyToManyField(related_name='cdia', to='Cronorgama.cdia')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime.now)),
                ('fecha_fin', models.DateTimeField(default=datetime.datetime(2023, 5, 20, 15, 6, 58, 68520))),
                ('Profesor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cdisponibilidad', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='Cronorgama.cdisponibilidad')),
            ],
        ),
    ]
