# Generated by Django 4.2 on 2023-05-15 05:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0012_cdia_cdisponibilidad_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignaturaXprofesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Asignatura', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.asignaturas')),
                ('Profesor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 0, 39, 46, 455358)),
        ),
        migrations.CreateModel(
            name='Ccalendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asigXprofe', models.ManyToManyField(related_name='asigXprofe', to='Cronorgama.asignaturaxprofesor')),
                ('dia', models.ForeignKey(blank=True, default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.dia')),
            ],
        ),
        migrations.CreateModel(
            name='calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.programas')),
            ],
        ),
    ]
