# Generated by Django 4.2 on 2023-05-15 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0013_asignaturaxprofesor_alter_disponibilidad_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='Programa',
        ),
        migrations.RemoveField(
            model_name='ccalendario',
            name='asigXprofe',
        ),
        migrations.RemoveField(
            model_name='ccalendario',
            name='dia',
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 2, 10, 948982)),
        ),
        migrations.DeleteModel(
            name='asignaturaXprofesor',
        ),
        migrations.DeleteModel(
            name='calendario',
        ),
        migrations.DeleteModel(
            name='Ccalendario',
        ),
    ]
