# Generated by Django 4.2 on 2023-05-15 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0015_asignaturaxprofesor_casigxprofe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 17, 44, 519878)),
        ),
    ]
