# Generated by Django 4.2 on 2023-05-15 06:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0019_alter_disponibilidad_fecha_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='cCalendario',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.ccalendario'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 22, 1, 44, 25, 960923)),
        ),
    ]
