# Generated by Django 4.2 on 2023-05-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0020_alter_calendario_ccalendario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='Programa',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='cCalendario',
        ),
        migrations.RemoveField(
            model_name='casigxprofe',
            name='asigXprofe',
        ),
        migrations.RemoveField(
            model_name='casigxprofe',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='ccalendario',
            name='asigXprofe',
        ),
        migrations.RemoveField(
            model_name='cdia',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='cdisponibilidad',
            name='cdia',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='Profesor',
        ),
        migrations.RemoveField(
            model_name='disponibilidad',
            name='cdisponibilidad',
        ),
        migrations.DeleteModel(
            name='asignaturaXprofesor',
        ),
        migrations.DeleteModel(
            name='calendario',
        ),
        migrations.DeleteModel(
            name='casigXprofe',
        ),
        migrations.DeleteModel(
            name='Ccalendario',
        ),
        migrations.DeleteModel(
            name='Cdia',
        ),
        migrations.DeleteModel(
            name='Cdisponibilidad',
        ),
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Disponibilidad',
        ),
    ]
