# Generated by Django 4.2 on 2023-05-15 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0021_remove_calendario_programa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignaturaXprofesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Asignatura', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.asignaturas')),
                ('Profesor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='casigXprofe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_inicioClase', models.TimeField()),
                ('hora_finClase', models.TimeField()),
                ('asigXprofe', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.asignaturaxprofesor')),
            ],
        ),
        migrations.CreateModel(
            name='Cdia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.BooleanField(default=0)),
                ('b', models.BooleanField(default=0)),
                ('c', models.BooleanField(default=0)),
                ('d', models.BooleanField(default=0)),
                ('e', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cdisponibilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cdia', models.ManyToManyField(related_name='cdia', to='Cronorgama.cdia')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Profesor', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cdisponibilidad', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad', to='Cronorgama.cdisponibilidad')),
            ],
        ),
        migrations.AddField(
            model_name='cdia',
            name='dia',
            field=models.ForeignKey(blank=True, default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.dia'),
        ),
        migrations.CreateModel(
            name='Ccalendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asigXprofe', models.ManyToManyField(related_name='casigXprofe', to='Cronorgama.casigxprofe')),
            ],
        ),
        migrations.AddField(
            model_name='casigxprofe',
            name='dia',
            field=models.ForeignKey(blank=True, default='', max_length=200, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.dia'),
        ),
        migrations.CreateModel(
            name='calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programa', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.programas')),
                ('cCalendario', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.ccalendario')),
            ],
        ),
    ]
