# Generated by Django 4.2 on 2023-05-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0023_alter_casigxprofe_hora_finclase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajesdisponibilidad',
            name='disponibilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.disponibilidad'),
        ),
    ]
