# Generated by Django 4.2 on 2023-05-23 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0024_alter_mensajesdisponibilidad_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiposalon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='salon',
            name='tipo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.tiposalon'),
        ),
    ]
