# Generated by Django 4.2 on 2023-05-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0025_tiposalon_alter_salon_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='habilitado',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
