# Generated by Django 4.2 on 2023-05-27 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0029_alter_mensajesdisponibilidad_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajesdisponibilidad',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='Cronorgama.disponibilidad'),
        ),
    ]
