# Generated by Django 4.2 on 2023-05-28 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0030_alter_mensajesdisponibilidad_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ccronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.asignaturas')),
            ],
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='id_asignaturas',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='id_authuser',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='id_programas',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='id_bitacora',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='registroasistencia',
            name='total_hora',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='material',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='Checkfecha_recuperar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='Checktema_recuperar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='checkAsistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='observaciones',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='Tema',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='semana',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha_recuperar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='hora_entrada',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='hora_salida',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='tema_recuperar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('Profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ccronograma', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Cronogramas', to='Cronorgama.ccronograma')),
                ('programa', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.programas')),
            ],
        ),
        migrations.AddField(
            model_name='ccronograma',
            name='bitacora',
            field=models.ManyToManyField(related_name='Ccronogramas', to='Cronorgama.bitacora'),
        ),
        migrations.AddField(
            model_name='ccronograma',
            name='registroAsistencia',
            field=models.ManyToManyField(related_name='resgistro_de_asistencia', to='Cronorgama.registroasistencia'),
        ),
    ]
