# Generated by Django 4.2 on 2023-05-28 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0031_ccronograma_remove_bitacora_id_asignaturas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cronorgama.asignaturas'),
        ),
    ]
