# Generated by Django 4.2 on 2023-05-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0032_cronograma_asignatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='BDcontratista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='hora',
        ),
        migrations.AddField(
            model_name='programacion',
            name='Cupo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacion',
            name='CupoG',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacion',
            name='CupoPostM',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programacion',
            name='Rsala',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='programacion',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
