# Generated by Django 4.2 on 2023-05-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0034_cprogramacion_remove_programacion_id_programas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cprogramacion',
            name='programacion',
            field=models.ManyToManyField(related_name='cprogramacion', to='Cronorgama.programacion'),
        ),
    ]
