# Generated by Django 4.2 on 2023-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0036_cdia_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
