# Generated by Django 4.2 on 2023-06-24 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0038_tapoyoxprograma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='Programa',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='cCalendario',
        ),
        migrations.RemoveField(
            model_name='casigxprofe',
            name='asigXprofe',
        ),
        migrations.RemoveField(
            model_name='casigxprofe',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='ccalendario',
            name='asigXprofe',
        ),
        migrations.AlterUniqueTogether(
            name='tapoyoxprograma',
            unique_together={('Tapoyo',)},
        ),
        migrations.DeleteModel(
            name='asignaturaXprofesor',
        ),
        migrations.DeleteModel(
            name='calendario',
        ),
        migrations.DeleteModel(
            name='casigXprofe',
        ),
        migrations.DeleteModel(
            name='Ccalendario',
        ),
    ]
