# Generated by Django 4.2 on 2023-06-24 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0039_remove_calendario_programa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccronograma',
            name='asignatura',
        ),
    ]
