# Generated by Django 4.2 on 2023-06-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0040_remove_ccronograma_asignatura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cdia',
            new_name='HorarioDia',
        ),
    ]
