# Generated by Django 4.2 on 2023-06-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cronorgama', '0041_rename_cdia_horariodia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cdisponibilidad',
            new_name='HorarioProfesor',
        ),
    ]
